// Lista ISO 3166-1 alpha-2 para el selector de país de envío (Mail Club).
// Nombres cortos ES/EN. El componente ordena por nombre localizado.
export interface Country {
  iso: string;
  es: string;
  en: string;
}

export const COUNTRIES: Country[] = [
  { iso: "DE", es: "Alemania", en: "Germany" },
  { iso: "AD", es: "Andorra", en: "Andorra" },
  { iso: "AO", es: "Angola", en: "Angola" },
  { iso: "SA", es: "Arabia Saudita", en: "Saudi Arabia" },
  { iso: "DZ", es: "Argelia", en: "Algeria" },
  { iso: "AR", es: "Argentina", en: "Argentina" },
  { iso: "AM", es: "Armenia", en: "Armenia" },
  { iso: "AU", es: "Australia", en: "Australia" },
  { iso: "AT", es: "Austria", en: "Austria" },
  { iso: "AZ", es: "Azerbaiyán", en: "Azerbaijan" },
  { iso: "BS", es: "Bahamas", en: "Bahamas" },
  { iso: "BD", es: "Bangladés", en: "Bangladesh" },
  { iso: "BB", es: "Barbados", en: "Barbados" },
  { iso: "BH", es: "Baréin", en: "Bahrain" },
  { iso: "BE", es: "Bélgica", en: "Belgium" },
  { iso: "BZ", es: "Belice", en: "Belize" },
  { iso: "BJ", es: "Benín", en: "Benin" },
  { iso: "BY", es: "Bielorrusia", en: "Belarus" },
  { iso: "BO", es: "Bolivia", en: "Bolivia" },
  { iso: "BA", es: "Bosnia y Herzegovina", en: "Bosnia and Herzegovina" },
  { iso: "BW", es: "Botsuana", en: "Botswana" },
  { iso: "BR", es: "Brasil", en: "Brazil" },
  { iso: "BN", es: "Brunéi", en: "Brunei" },
  { iso: "BG", es: "Bulgaria", en: "Bulgaria" },
  { iso: "BF", es: "Burkina Faso", en: "Burkina Faso" },
  { iso: "BI", es: "Burundi", en: "Burundi" },
  { iso: "BT", es: "Bután", en: "Bhutan" },
  { iso: "CV", es: "Cabo Verde", en: "Cape Verde" },
  { iso: "KH", es: "Camboya", en: "Cambodia" },
  { iso: "CM", es: "Camerún", en: "Cameroon" },
  { iso: "CA", es: "Canadá", en: "Canada" },
  { iso: "QA", es: "Catar", en: "Qatar" },
  { iso: "TD", es: "Chad", en: "Chad" },
  { iso: "CL", es: "Chile", en: "Chile" },
  { iso: "CN", es: "China", en: "China" },
  { iso: "CY", es: "Chipre", en: "Cyprus" },
  { iso: "VA", es: "Ciudad del Vaticano", en: "Vatican City" },
  { iso: "CO", es: "Colombia", en: "Colombia" },
  { iso: "KM", es: "Comoras", en: "Comoros" },
  { iso: "CG", es: "Congo", en: "Congo" },
  { iso: "KP", es: "Corea del Norte", en: "North Korea" },
  { iso: "KR", es: "Corea del Sur", en: "South Korea" },
  { iso: "CR", es: "Costa Rica", en: "Costa Rica" },
  { iso: "CI", es: "Costa de Marfil", en: "Ivory Coast" },
  { iso: "HR", es: "Croacia", en: "Croatia" },
  { iso: "CU", es: "Cuba", en: "Cuba" },
  { iso: "DK", es: "Dinamarca", en: "Denmark" },
  { iso: "DM", es: "Dominica", en: "Dominica" },
  { iso: "EC", es: "Ecuador", en: "Ecuador" },
  { iso: "EG", es: "Egipto", en: "Egypt" },
  { iso: "SV", es: "El Salvador", en: "El Salvador" },
  { iso: "AE", es: "Emiratos Árabes Unidos", en: "United Arab Emirates" },
  { iso: "ER", es: "Eritrea", en: "Eritrea" },
  { iso: "SK", es: "Eslovaquia", en: "Slovakia" },
  { iso: "SI", es: "Eslovenia", en: "Slovenia" },
  { iso: "ES", es: "España", en: "Spain" },
  { iso: "US", es: "Estados Unidos", en: "United States" },
  { iso: "EE", es: "Estonia", en: "Estonia" },
  { iso: "SZ", es: "Esuatini", en: "Eswatini" },
  { iso: "ET", es: "Etiopía", en: "Ethiopia" },
  { iso: "PH", es: "Filipinas", en: "Philippines" },
  { iso: "FI", es: "Finlandia", en: "Finland" },
  { iso: "FJ", es: "Fiyi", en: "Fiji" },
  { iso: "FR", es: "Francia", en: "France" },
  { iso: "GA", es: "Gabón", en: "Gabon" },
  { iso: "GM", es: "Gambia", en: "Gambia" },
  { iso: "GE", es: "Georgia", en: "Georgia" },
  { iso: "GH", es: "Ghana", en: "Ghana" },
  { iso: "GD", es: "Granada", en: "Grenada" },
  { iso: "GR", es: "Grecia", en: "Greece" },
  { iso: "GT", es: "Guatemala", en: "Guatemala" },
  { iso: "GY", es: "Guyana", en: "Guyana" },
  { iso: "GN", es: "Guinea", en: "Guinea" },
  { iso: "GQ", es: "Guinea Ecuatorial", en: "Equatorial Guinea" },
  { iso: "GW", es: "Guinea-Bisáu", en: "Guinea-Bissau" },
  { iso: "HT", es: "Haití", en: "Haiti" },
  { iso: "HN", es: "Honduras", en: "Honduras" },
  { iso: "HU", es: "Hungría", en: "Hungary" },
  { iso: "IN", es: "India", en: "India" },
  { iso: "ID", es: "Indonesia", en: "Indonesia" },
  { iso: "IQ", es: "Irak", en: "Iraq" },
  { iso: "IR", es: "Irán", en: "Iran" },
  { iso: "IE", es: "Irlanda", en: "Ireland" },
  { iso: "IS", es: "Islandia", en: "Iceland" },
  { iso: "IL", es: "Israel", en: "Israel" },
  { iso: "IT", es: "Italia", en: "Italy" },
  { iso: "JM", es: "Jamaica", en: "Jamaica" },
  { iso: "JP", es: "Japón", en: "Japan" },
  { iso: "JO", es: "Jordania", en: "Jordan" },
  { iso: "KZ", es: "Kazajistán", en: "Kazakhstan" },
  { iso: "KE", es: "Kenia", en: "Kenya" },
  { iso: "KG", es: "Kirguistán", en: "Kyrgyzstan" },
  { iso: "KI", es: "Kiribati", en: "Kiribati" },
  { iso: "XK", es: "Kosovo", en: "Kosovo" },
  { iso: "KW", es: "Kuwait", en: "Kuwait" },
  { iso: "LA", es: "Laos", en: "Laos" },
  { iso: "LS", es: "Lesoto", en: "Lesotho" },
  { iso: "LV", es: "Letonia", en: "Latvia" },
  { iso: "LB", es: "Líbano", en: "Lebanon" },
  { iso: "LR", es: "Liberia", en: "Liberia" },
  { iso: "LY", es: "Libia", en: "Libya" },
  { iso: "LI", es: "Liechtenstein", en: "Liechtenstein" },
  { iso: "LT", es: "Lituania", en: "Lithuania" },
  { iso: "LU", es: "Luxemburgo", en: "Luxembourg" },
  { iso: "MK", es: "Macedonia del Norte", en: "North Macedonia" },
  { iso: "MG", es: "Madagascar", en: "Madagascar" },
  { iso: "MY", es: "Malasia", en: "Malaysia" },
  { iso: "MW", es: "Malaui", en: "Malawi" },
  { iso: "MV", es: "Maldivas", en: "Maldives" },
  { iso: "ML", es: "Malí", en: "Mali" },
  { iso: "MT", es: "Malta", en: "Malta" },
  { iso: "MA", es: "Marruecos", en: "Morocco" },
  { iso: "MU", es: "Mauricio", en: "Mauritius" },
  { iso: "MR", es: "Mauritania", en: "Mauritania" },
  { iso: "MX", es: "México", en: "Mexico" },
  { iso: "MD", es: "Moldavia", en: "Moldova" },
  { iso: "MC", es: "Mónaco", en: "Monaco" },
  { iso: "MN", es: "Mongolia", en: "Mongolia" },
  { iso: "ME", es: "Montenegro", en: "Montenegro" },
  { iso: "MZ", es: "Mozambique", en: "Mozambique" },
  { iso: "MM", es: "Myanmar", en: "Myanmar" },
  { iso: "NA", es: "Namibia", en: "Namibia" },
  { iso: "NR", es: "Nauru", en: "Nauru" },
  { iso: "NP", es: "Nepal", en: "Nepal" },
  { iso: "NI", es: "Nicaragua", en: "Nicaragua" },
  { iso: "NE", es: "Níger", en: "Niger" },
  { iso: "NG", es: "Nigeria", en: "Nigeria" },
  { iso: "NO", es: "Noruega", en: "Norway" },
  { iso: "NZ", es: "Nueva Zelanda", en: "New Zealand" },
  { iso: "OM", es: "Omán", en: "Oman" },
  { iso: "NL", es: "Países Bajos", en: "Netherlands" },
  { iso: "PK", es: "Pakistán", en: "Pakistan" },
  { iso: "PW", es: "Palaos", en: "Palau" },
  { iso: "PS", es: "Palestina", en: "Palestine" },
  { iso: "PA", es: "Panamá", en: "Panama" },
  { iso: "PG", es: "Papúa Nueva Guinea", en: "Papua New Guinea" },
  { iso: "PY", es: "Paraguay", en: "Paraguay" },
  { iso: "PE", es: "Perú", en: "Peru" },
  { iso: "PL", es: "Polonia", en: "Poland" },
  { iso: "PT", es: "Portugal", en: "Portugal" },
  { iso: "GB", es: "Reino Unido", en: "United Kingdom" },
  { iso: "CF", es: "República Centroafricana", en: "Central African Republic" },
  { iso: "CZ", es: "República Checa", en: "Czechia" },
  { iso: "CD", es: "Rep. Democrática del Congo", en: "DR Congo" },
  { iso: "DO", es: "República Dominicana", en: "Dominican Republic" },
  { iso: "RW", es: "Ruanda", en: "Rwanda" },
  { iso: "RO", es: "Rumania", en: "Romania" },
  { iso: "RU", es: "Rusia", en: "Russia" },
  { iso: "WS", es: "Samoa", en: "Samoa" },
  { iso: "KN", es: "San Cristóbal y Nieves", en: "Saint Kitts and Nevis" },
  { iso: "SM", es: "San Marino", en: "San Marino" },
  { iso: "VC", es: "San Vicente y las Granadinas", en: "Saint Vincent and the Grenadines" },
  { iso: "LC", es: "Santa Lucía", en: "Saint Lucia" },
  { iso: "ST", es: "Santo Tomé y Príncipe", en: "Sao Tome and Principe" },
  { iso: "SN", es: "Senegal", en: "Senegal" },
  { iso: "RS", es: "Serbia", en: "Serbia" },
  { iso: "SC", es: "Seychelles", en: "Seychelles" },
  { iso: "SL", es: "Sierra Leona", en: "Sierra Leone" },
  { iso: "SG", es: "Singapur", en: "Singapore" },
  { iso: "SY", es: "Siria", en: "Syria" },
  { iso: "SO", es: "Somalia", en: "Somalia" },
  { iso: "LK", es: "Sri Lanka", en: "Sri Lanka" },
  { iso: "ZA", es: "Sudáfrica", en: "South Africa" },
  { iso: "SD", es: "Sudán", en: "Sudan" },
  { iso: "SS", es: "Sudán del Sur", en: "South Sudan" },
  { iso: "SE", es: "Suecia", en: "Sweden" },
  { iso: "CH", es: "Suiza", en: "Switzerland" },
  { iso: "SR", es: "Surinam", en: "Suriname" },
  { iso: "TH", es: "Tailandia", en: "Thailand" },
  { iso: "TW", es: "Taiwán", en: "Taiwan" },
  { iso: "TZ", es: "Tanzania", en: "Tanzania" },
  { iso: "TJ", es: "Tayikistán", en: "Tajikistan" },
  { iso: "TL", es: "Timor Oriental", en: "Timor-Leste" },
  { iso: "TG", es: "Togo", en: "Togo" },
  { iso: "TO", es: "Tonga", en: "Tonga" },
  { iso: "TT", es: "Trinidad y Tobago", en: "Trinidad and Tobago" },
  { iso: "TN", es: "Túnez", en: "Tunisia" },
  { iso: "TM", es: "Turkmenistán", en: "Turkmenistan" },
  { iso: "TR", es: "Turquía", en: "Turkey" },
  { iso: "TV", es: "Tuvalu", en: "Tuvalu" },
  { iso: "UA", es: "Ucrania", en: "Ukraine" },
  { iso: "UG", es: "Uganda", en: "Uganda" },
  { iso: "UY", es: "Uruguay", en: "Uruguay" },
  { iso: "UZ", es: "Uzbekistán", en: "Uzbekistan" },
  { iso: "VU", es: "Vanuatu", en: "Vanuatu" },
  { iso: "VE", es: "Venezuela", en: "Venezuela" },
  { iso: "VN", es: "Vietnam", en: "Vietnam" },
  { iso: "YE", es: "Yemen", en: "Yemen" },
  { iso: "DJ", es: "Yibuti", en: "Djibouti" },
  { iso: "ZM", es: "Zambia", en: "Zambia" },
  { iso: "ZW", es: "Zimbabue", en: "Zimbabwe" },
  { iso: "AG", es: "Antigua y Barbuda", en: "Antigua and Barbuda" },
  { iso: "AL", es: "Albania", en: "Albania" },
  { iso: "AW", es: "Aruba", en: "Aruba" },
  { iso: "AX", es: "Islas Åland", en: "Åland Islands" },
  { iso: "BL", es: "San Bartolomé", en: "Saint Barthélemy" },
  { iso: "BM", es: "Bermudas", en: "Bermuda" },
  { iso: "BQ", es: "Caribe neerlandés", en: "Caribbean Netherlands" },
  { iso: "CK", es: "Islas Cook", en: "Cook Islands" },
  { iso: "CW", es: "Curazao", en: "Curaçao" },
  { iso: "EH", es: "Sáhara Occidental", en: "Western Sahara" },
  { iso: "FK", es: "Islas Malvinas", en: "Falkland Islands" },
  { iso: "FO", es: "Islas Feroe", en: "Faroe Islands" },
  { iso: "GF", es: "Guayana Francesa", en: "French Guiana" },
  { iso: "GG", es: "Guernesey", en: "Guernsey" },
  { iso: "GI", es: "Gibraltar", en: "Gibraltar" },
  { iso: "GL", es: "Groenlandia", en: "Greenland" },
  { iso: "GP", es: "Guadalupe", en: "Guadeloupe" },
  { iso: "GU", es: "Guam", en: "Guam" },
  { iso: "IM", es: "Isla de Man", en: "Isle of Man" },
  { iso: "IO", es: "Territorio Británico del Índico", en: "British Indian Ocean Territory" },
  { iso: "JE", es: "Jersey", en: "Jersey" },
  { iso: "MF", es: "San Martín (parte francesa)", en: "Saint Martin (French part)" },
  { iso: "MH", es: "Islas Marshall", en: "Marshall Islands" },
  { iso: "MQ", es: "Martinica", en: "Martinique" },
  { iso: "MS", es: "Montserrat", en: "Montserrat" },
  { iso: "NC", es: "Nueva Caledonia", en: "New Caledonia" },
  { iso: "NF", es: "Isla Norfolk", en: "Norfolk Island" },
  { iso: "NU", es: "Niue", en: "Niue" },
  { iso: "PF", es: "Polinesia Francesa", en: "French Polynesia" },
  { iso: "PM", es: "San Pedro y Miquelón", en: "Saint Pierre and Miquelon" },
  { iso: "PN", es: "Islas Pitcairn", en: "Pitcairn Islands" },
  { iso: "PR", es: "Puerto Rico", en: "Puerto Rico" },
  { iso: "RE", es: "Reunión", en: "Réunion" },
  { iso: "SB", es: "Islas Salomón", en: "Solomon Islands" },
  { iso: "SH", es: "Santa Elena", en: "Saint Helena" },
  { iso: "SJ", es: "Svalbard y Jan Mayen", en: "Svalbard and Jan Mayen" },
  { iso: "SX", es: "Sint Maarten", en: "Sint Maarten" },
  { iso: "TC", es: "Islas Turcas y Caicos", en: "Turks and Caicos Islands" },
  { iso: "TF", es: "Territorios Australes Franceses", en: "French Southern Territories" },
  { iso: "TK", es: "Tokelau", en: "Tokelau" },
  { iso: "UM", es: "Islas ultramarinas de EE. UU.", en: "US Minor Outlying Islands" },
  { iso: "VG", es: "Islas Vírgenes Británicas", en: "British Virgin Islands" },
  { iso: "VI", es: "Islas Vírgenes de EE. UU.", en: "US Virgin Islands" },
  { iso: "WF", es: "Wallis y Futuna", en: "Wallis and Futuna" },
  { iso: "YT", es: "Mayotte", en: "Mayotte" },
];

export function countryName(iso: string, lang: "es" | "en" = "es"): string {
  return COUNTRIES.find((c) => c.iso === iso)?.[lang] ?? iso;
}

// Set de destinos habilitados para envío. El servidor rechaza cualquier
// código fuera de esta lista (nunca confiar en el <select> del navegador).
export const SUPPORTED_COUNTRY_ISO: ReadonlySet<string> = new Set(
  COUNTRIES.map((c) => c.iso),
);
