-- Editions
create table if not exists public.editions (
  id bigint primary key generated by default as identity,
  edition_number int not null,
  title text not null,
  description text not null,
  cover_url text not null,
  pdf_url text,
  featured boolean default false,
  badge text,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Edition pages (for page-flip viewer)
create table if not exists public.edition_pages (
  id bigint primary key generated by default as identity,
  edition_id bigint not null references public.editions(id) on delete cascade,
  page_number int not null,
  image_url text not null,
  alt_text text not null,
  created_at timestamptz not null default now()
);

-- Enable RLS
alter table public.editions enable row level security;
alter table public.edition_pages enable row level security;

-- Anyone can read editions
drop policy if exists "Anyone can read editions" on public.editions;
create policy "Anyone can read editions"
  on public.editions for select
  using (true);

-- Anyone can read edition pages
drop policy if exists "Anyone can read edition pages" on public.edition_pages;
create policy "Anyone can read edition pages"
  on public.edition_pages for select
  using (true);

-- Grants
grant all on public.editions to service_role, anon, authenticated;
grant all on public.edition_pages to service_role, anon, authenticated;

-- Expose to API
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'editions'
  ) then
    alter publication supabase_realtime add table public.editions;
  end if;
end
$$;
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'edition_pages'
  ) then
    alter publication supabase_realtime add table public.edition_pages;
  end if;
end
$$;
