-- Bilingual editions (EXPAND step)
-- The "issue" (editions) is one product published in two languages. Its localized
-- content (title/description/cover/pdf/badge) moves to edition_languages.
-- Legacy content columns on editions stay here until 019 (CONTRACT) after the app
-- has been verified on the new structure. Do NOT drop them in this migration.
--
-- Also: at most one magazine can share an edition_number (getEditionBySlug uses .single()).

create table if not exists public.edition_languages (
  id bigint primary key generated by default as identity,
  edition_id bigint not null references public.editions(id) on delete cascade,
  language text not null check (language in ('es', 'en')),
  title text not null,
  description text not null default '',
  cover_url text,
  pdf_url text,
  badge text,
  created_at timestamptz not null default now()
);

-- One localized version per issue per language
alter table public.edition_languages drop constraint if exists edition_languages_edition_id_language_key;
alter table public.edition_languages
  add constraint edition_languages_edition_id_language_key unique (edition_id, language);

-- Backfill: every existing edition becomes an issue with its ES version (legacy content).
insert into public.edition_languages (edition_id, language, title, description, cover_url, pdf_url, badge)
select id, 'es', title, description, cover_url, pdf_url, badge
from public.editions
on conflict (edition_id, language) do nothing;

-- Edition language ids must never collide with editions.id: /api/pdf/{id} resolves
-- the id ambiguously (edition_languages.id OR legacy editions.id). Renumber above
-- any realistic edition id (1000000 + edition_id*10 + [en=1]), and keep the
-- identity sequence above that range. Guarded so re-runs only touch legacy-range ids.
update public.edition_languages
set id = 1000000 + edition_id * 10 + case when language = 'en' then 1 else 0 end
where id < 1000000;

select setval('public.edition_languages_id_seq',
              (select greatest(max(id) + 1, 1000000) from public.edition_languages),
              false);

-- Prevent duplicate edition numbers (magazine). Nulls (free articles) allowed.
create unique index if not exists editions_edition_number_unique
  on public.editions (edition_number)
  where edition_number is not null;

-- RLS: anyone can read localized versions (same as editions)
alter table public.edition_languages enable row level security;

drop policy if exists "Anyone can read edition languages" on public.edition_languages;
create policy "Anyone can read edition languages"
  on public.edition_languages for select
  using (true);

grant all on public.edition_languages to service_role, anon, authenticated;

-- Expose to API (future realtime carousel)
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'edition_languages'
  ) then
    alter publication supabase_realtime add table public.edition_languages;
  end if;
end
$$;